apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrea-quaisie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andrea-quaisie
  template:
    metadata:
      labels:
        app: andrea-quaisie
    spec:
      containers:
      - name: andrea-quaisie
        image: node:14
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: andrea-pod-service
spec:
  selector:
    app: andrea-quaisie
  type: LoadBalancer
  parts:
  - port: 80
    targetPort: 80
---





