apiVersion: apps/v1
kind: Deployment
metadata:
  name: andrea-quaisie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andrea-quaisie
  template:
    metadata:
      labels:
        app: andrea-quaisie
    spec:
      containers:
      - name: andrea-quaisie
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250m
          requests:
            cpu: 50m
            memory: 100m






