apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eduardo-urbiola
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: eduardo-urbiola
  template:
    metadata:
      labels:
        app: eduardo-urbiola
    spec:
      containers:
      - name: eduardo-urbiola
        image: gcr.io/team-not-found/teamwebsite
        ports:
        - containerPort: 3000
        resources: 
          limits:
            cpu: 100m
            memory: 250M
          requests:
              cpu: 50m
              memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: eduardo-pod-service
spec:
  selector:
    app: eduardo-urbiola
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 80

