apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eduardo-urbiola
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: eduardo-urbiola
  template:
    metadata:
      labels:
        app: eduardo-urbiola
    spec:
      containers:
      - name: eduardo-urbiola
        image: busybox
        ports:
        - containerPort: 80
        resources: 
          limits:
            cpu: 100m
            memory: 250M
          requests:
              cpu: 50m
              memory: 100M
