apiVersion: apps/v1
kind: Deployment
metadata:
  name: jared-neal
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: jared-neal
  template:
    metadata:
      labels:
        app: jared-neal
    spec: 
      containers:
      - name: jared-neal
        image: gcr.io/team-not-found/teamwebsite
        ports: 
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: jared-pod-service
spec:
  selector:
    app: jared-neal
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80