apiVersion: apps/v1
kind: Deployment
metadata:
  name: maddie-christensen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maddie-christensen
  template:
    metadata:
      labels:
        app: maddie-christensen
    spec:
      containers:
      - name: maddie-christensen
        image: gcr.io/team-not-found/teamwebsite
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250m
          requests:
            cpu: 50m
            memory: 100m
---
apiVersion: v1
kind: Service
metadata: 
  name: maddiepod-service
spec:
  selector:
    app: maddie-christensen
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
